language: node_js
dist: trusty
node_js: 6

matrix:
  include:
    - os: linux
      env:
        - BOOST_URL=http://sourceforge.net/projects/boost/files/boost/1.61.0/boost_1_61_0.tar.gz
        - BOOST_ROOT=$TRAVIS_BUILD_DIR/deps/boost
        - CMAKE_URL=https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz
        - CMAKE_ROOT=$TRAVIS_BUILD_DIR/deps/cmake
        - PATH=$CMAKE_ROOT/bin:$PATH
    - os: osx

addons:
  apt:
    packages:
      - libudev-dev

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
        # Install Boost
        mkdir -p $BOOST_ROOT
        travis_retry curl -sSL $BOOST_URL | tar xz --strip-components=1 -C $BOOST_ROOT
        pushd $BOOST_ROOT
        ./bootstrap.sh
        ./b2 toolset=gcc cxxflags=-fPIC cflags=-fPIC address-model=64 link=static \
            --with-thread --with-system --with-regex --with-date_time --with-chrono
        popd

        # Install CMake
        mkdir -p $CMAKE_ROOT
        travis_retry curl -sSL $CMAKE_URL | tar xz --strip-components=1 -C $CMAKE_ROOT
    fi

    # TODO: Decrypt code signing certificate on macOS

script:
  - npm run build
  - npm test
  - npm run test-e2e

after_success:
  - npm run electron-builder
